// Barrel export para componentes comunes
export { Button } from './Button';
export { Input } from './Input';
export { Select } from './Select';
export { Modal } from './Modal';
export { Badge } from './Badge';
export { Card } from './Card';
export { Table } from './Table';
export { StatCard } from './StatCard';
export { SearchBar } from './SearchBar';
export { SearchResults } from './SearchResults';
